### ISSUE TITLE
TestMain.hs C++ compilation errors on gcc 5.1

### ISSUE THREAD

**Issue by kasbah** [andyarvanitis/purescript-native#9]
I just assumed this is supposed to be working. Let me know if that is not the case or I am doing something stupid. I just ran `runghc pcc/TestMain.hs` from the root of the repo and modified TestMain.hs slightly to get the different compilers into CMake. 

~~clang 3.6~~
~~[full output](https://gist.github.com/kasbah/5c82d0bc1eb8e80405ca)~~

gcc 5.1

```
...
[ 87%] Building CXX object CMakeFiles/Main.dir/Main/Main.cc.o
In file included from /home/kaspar/projects/purescript/pure14/pcc-tests/output/Main/Main.hh:6:0,
                 from /home/kaspar/projects/purescript/pure14/pcc-tests/output/Main/Main.cc:6:
/home/kaspar/projects/purescript/pure14/pcc-tests/output/Prelude/Prelude.hh: In instantiation of ‘A Main::f(PureScript::param<T>) [with A = std::basic_string<char>; PureScript::param<T> = const std::basic_string<char>&]’:
/home/kaspar/projects/purescript/pure14/pcc-tests/output/Main/Main.cc:15:109:   required from here
/home/kaspar/projects/purescript/pure14/pcc-tests/output/Prelude/Prelude.hh:563:19: error: specialization of ‘template<template<class, class> class A, class ...> template<class T> const A<T, T> Prelude::Category<A, <template-parameter-1-2> >::id<T>’ must appear at namespace scope
     const fn<T,T> Category<fn>::id = [](param<T> x) -> T {
                   ^
make[2]: *** [CMakeFiles/Main.dir/Main/Main.cc.o] Error 1
make[1]: *** [CMakeFiles/Main.dir/all] Error 2
make: *** [all] Error 2
TestMain.hs: callProcess: make (exit 2): failed
```

[full output](https://gist.github.com/kasbah/b902235e8c7d06b06483)

**Comment by kasbah** [comment]
I just realized I accidentally put in `clang` not `clang++` and that was the cause of the clang build failing. GCC/G++ build was correct though, so there appear to be some remaining incompatibilities there. 

Maybe you want to close this as wontfix :)

**Comment by andyarvanitis** [comment]
I just tried gcc 5.2.0 (latest stable release), and things are a bit better, but there are still issues. I plan to start tackling them once I get a few more core tests running.

**Comment by andyarvanitis** [comment]
I've been working on an alt design/implementation of the backend, and it's looking like it might become the primary version. It works fine with gcc 4.9.2 (tested on Debian 8.2 stable), so stay tuned.

**Comment by andyarvanitis** [comment]
Switched over to new C++11 based approach, so gcc support is no longer an issue.
